-- MySQL Script generated by MySQL Workbench
-- ven 30 giu 2017 20:20:04 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema slim3_auth
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `slim3_auth` ;

-- -----------------------------------------------------
-- Schema slim3_auth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `slim3_auth` DEFAULT CHARACTER SET utf8 ;
USE `slim3_auth` ;

-- -----------------------------------------------------
-- Table `slim3_auth`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slim3_auth`.`user` ;

CREATE TABLE IF NOT EXISTS `slim3_auth`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `session` TEXT NOT NULL,
  `disabled` TINYINT(1) NOT NULL DEFAULT '0',
  `created_date` DATETIME NOT NULL DEFAULT NOW(),
  `modification_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
